In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [3]:
x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]])
y = array([4,5,6,7])

In [4]:
print('x shape : ', x.shape) 
print('y shape : ', y.shape)

x shape :  (4, 3)
y shape :  (4,)


In [5]:
# 2. Model

model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(3,1)))

# Dense
model.add(Dense(5))
model.add(Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 10)                480       
                                                                 
 dense (Dense)               (None, 5)                 55        
                                                                 
 dense_1 (Dense)             (None, 1)                 6         
                                                                 
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


In [8]:
# Early stopping

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='loss', patience=100, mode='auto')

In [10]:
# 3. Fit model

model.compile(optimizer='adam', loss='mse')
##model.fit(x, y, epochs=100, batch_size=1)

# with early stopping
model.fit(x, y, epochs=1000, batch_size=1, verbose=2, callbacks=[early_stopping])


x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)

Epoch 1/1000
4/4 - 1s - loss: 0.0059 - 892ms/epoch - 223ms/step
Epoch 2/1000
4/4 - 0s - loss: 0.0029 - 18ms/epoch - 4ms/step
Epoch 3/1000
4/4 - 0s - loss: 0.0025 - 12ms/epoch - 3ms/step
Epoch 4/1000
4/4 - 0s - loss: 0.0019 - 21ms/epoch - 5ms/step
Epoch 5/1000
4/4 - 0s - loss: 0.0017 - 13ms/epoch - 3ms/step
Epoch 6/1000
4/4 - 0s - loss: 0.0011 - 14ms/epoch - 4ms/step
Epoch 7/1000
4/4 - 0s - loss: 9.9861e-04 - 12ms/epoch - 3ms/step
Epoch 8/1000
4/4 - 0s - loss: 7.6336e-04 - 11ms/epoch - 3ms/step
Epoch 9/1000
4/4 - 0s - loss: 0.0010 - 12ms/epoch - 3ms/step
Epoch 10/1000
4/4 - 0s - loss: 6.6615e-04 - 17ms/epoch - 4ms/step
Epoch 11/1000
4/4 - 0s - loss: 0.0012 - 14ms/epoch - 3ms/step
Epoch 12/1000
4/4 - 0s - loss: 8.5780e-04 - 15ms/epoch - 4ms/step
Epoch 13/1000
4/4 - 0s - loss: 9.1401e-04 - 14ms/epoch - 3ms/step
Epoch 14/1000
4/4 - 0s - loss: 5.6325e-04 - 13ms/epoch - 3ms/step
Epoch 15/1000
4/4 - 0s - loss: 8.8529e-04 - 16ms/epoch - 4ms/step
Epoch 16/1000
4/4 - 0s - loss: 0.0014 - 14ms/epo

In [ ]:
# LSTM with DNN
 
a = np.array(range(1,11))
 
size = 5
 
def split_x(seq, size):
    aaa = []
    for i in range(len(seq) - size + 1):
        subset = seq[i:(i+size)]
        aaa.append([item for item in subset])
    print(type(aaa))
    return np.array(aaa)
 
dataset = split_x(a, size)
print('------------------')
print(dataset)
 
# RESULT
# size = 5
# [[ 1  2  3  4  5]
#  [ 2  3  4  5  6]
#  [ 3  4  5  6  7]
#  [ 4  5  6  7  8]
#  [ 5  6  7  8  9]
#  [ 6  7  8  9 10]]
 
# 시계열 데이터는 y값이 없는 경우 많다.
# a로 y 만듬 
 
x_train = dataset[:, 0:-1]
y_train = dataset[:, -1] # [:, 4]
 
print(x_train.shape) # (6, 4)
print(y_train.shape) # (6, )
 
# x_train
# [[1 2 3 4]
#  [2 3 4 5]
#  [3 4 5 6]
#  [4 5 6 7]
#  [5 6 7 8]
#  [6 7 8 9]]
# y_train
# [ 5  6  7  8  9 10]
 
model = Sequential()
model.add(Dense(33, activation = 'relu', input_shape=(4,)))
model.add(Dense(5))
model.add(Dense(1))
# LSTM을 DNN으로 구현 가능
 
model.compile(optimizer='adam', loss='mse')
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=2)
 
x_input = np.array([7,8,9,10]) # (4,)
x_input = x_input.reshape(1,4)
 
yhat = model.predict(x_input)
print(yhat)